[package]
name = "map-alg-playground"
version = "0.1.0"
edition = "2021"
authors = ["Alexander Solovyov"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nannou = "0.19.0"
rand = "0.8.5"